# -------------------------
# Iceberg sink
# -------------------------

debezium.sink.type=iceberg

debezium.sink.iceberg.catalog-name=cdc_catalog
debezium.sink.iceberg.catalog-impl=org.apache.iceberg.jdbc.JdbcCatalog

debezium.sink.iceberg.uri=jdbc:postgresql://postgres:5432/cdc_lab
debezium.sink.iceberg.jdbc.user=postgres
debezium.sink.iceberg.jdbc.password=postgres

debezium.sink.iceberg.table-namespace=cdc

debezium.sink.iceberg.warehouse=s3://warehouse/iceberg

debezium.sink.iceberg.io-impl=org.apache.iceberg.io.ResolvingFileIO

debezium.sink.iceberg.s3.endpoint=http://minio:9000
debezium.sink.iceberg.s3.access-key-id=minioadmin
debezium.sink.iceberg.s3.secret-access-key=minioadmin
debezium.sink.iceberg.s3.path-style-access=true
debezium.sink.iceberg.client.region=us-east-1

debezium.sink.iceberg.upsert=true
debezium.sink.iceberg.upsert-keep-deletes=false
debezium.sink.iceberg.write.format.default=parquet
debezium.sink.iceberg.allow-field-addition=true


# -------------------------
# Event format
# -------------------------

debezium.format.value=json
debezium.format.key=json

debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.add.fields=op,table,source.ts_ns,db
debezium.transforms.unwrap.delete.tombstone.handling.mode=rewrite
debezium.transforms.unwrap.drop.tombstones=true


# -------------------------
# PostgreSQL source
# -------------------------

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector

debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres
debezium.source.database.dbname=cdc_lab

debezium.source.topic.prefix=cdc

debezium.source.plugin.name=pgoutput
debezium.source.slot.name=cdc_slot

debezium.source.publication.name=cdc_publication
debezium.source.publication.autocreate.mode=disabled

debezium.source.table.include.list=public.customers

debezium.source.snapshot.mode=initial


# -------------------------
# Debezium state
# -------------------------

debezium.source.offset.storage=io.debezium.server.iceberg.offset.IcebergOffsetBackingStore
debezium.source.offset.storage.iceberg.table-name=_debezium_offset_storage

debezium.source.schema.history.internal=io.debezium.server.iceberg.history.IcebergSchemaHistory
debezium.source.schema.history.internal.iceberg.table-name=_debezium_database_history_storage

debezium.source.offset.flush.interval.ms=0

quarkus.log.level=INFO
